### ISSUE TITLE
Error: expected frame header but was not found. FLAC files parsed with id3v2 parser?

### ISSUE THREAD

**Issue by sspilleman** [leetreveil/musicmetadata#133]
Hi!

1st I'd like to say many thanks for offering and maintaining your lib, I like it a lot.

I'd like to share the following issue. When parsing FLAC files i get errors like this:

```
Error: expected frame header but was not found
    at seekFirstAudioFrame (/tmp/music/node_modules/musicmetadata/lib/id3v2.js:174:21)
    at /tmp/music/node_modules/musicmetadata/lib/id3v2.js:63:18
    at emitData (/tmp/music/node_modules/strtok2/lib/strtok.js:351:20)
    at Stream.dataListener (/tmp/music/node_modules/strtok2/lib/strtok.js:414:11)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at Stream.<anonymous> (/tmp/music/node_modules/musicmetadata/lib/index.js:69:13)
    at Stream.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
```

Looking @ the error is see the error is thrown by lib/id3v2.js. Is that correct at all? As I would assume that in case of flac files the parsing would be handled by lib/flac.js...

Any ideas?

Thanx!

Sander

**Comment by leetreveil** [comment]
Can you send me the file that's causing the error?

**Comment by leetreveil** [comment]
Did you send me the file for this? Feel free to re-open.
