### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by floydpink** [leetreveil/musicmetadata#88]
The comment I posted on #87 was because I thought the issue I have is related to that, but apparently not.

When running from the node environment, things used to work until v.06.6, but with v1.0.0 I am getting this error (possibly because I need to make changes to adapt to the new API):

```
/Users/swara/swara-server/mean-app/node_modules/musicmetadata/lib/index.js:66
    }, done, opts.hasOwnProperty('duration'), fsize);
                 ^
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Stream.<anonymous> (/Users/swara/swara-server/mean-app/node_modules/musicmetadata/lib/index.js:66:18)
    at Stream.g (events.js:199:16)
    at Stream.emit (events.js:107:17)
    at drain (/Users/swara/swara-server/mean-app/node_modules/musicmetadata/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/swara/swara-server/mean-app/node_modules/musicmetadata/node_modules/through/index.js:45:5)
    at Stream.write (/Users/swara/swara-server/mean-app/node_modules/musicmetadata/node_modules/through/index.js:14:43)
    at Stream.stream.write (/Users/swara/swara-server/mean-app/node_modules/musicmetadata/node_modules/through/index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

Thanks

**Comment by floydpink** [comment]
This was just the case not looking into the breaking changes - when the calling code was adapted to use the callback API instead of the EventEmitter one, the error went away.
